#!/bin/sh

uci set argon.@global[0].online_wallpaper='none'
uci set argon.@global[0].mode='light'
uci set argon.@global[0].primary='#e879a8'
uci set argon.@global[0].dark_primary='#c9719f'
uci set argon.@global[0].transparency='0.4'
uci set argon.@global[0].transparency_dark='0.4'
uci commit argon

exit 0
